//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the SergeyPetrachkov VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects
//

import Foundation
import UIKit
import SiberianVIPER

struct ___VARIABLE_moduleName___Model: CollectionModelGeneric {
  static var anyViewType: UIView.Type {
    return ___VARIABLE_moduleName___Cell.self
  }
  
  let currentModel: Any
  
  func setup(view: ___VARIABLE_moduleName___Cell) {
    
  }
}
class ___VARIABLE_moduleName___Cell: UITableViewCell {
  
}
