//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the SergeyPetrachkov VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects.
//

import UIKit

protocol ___VARIABLE_moduleName___ServiceProtocol: class {
  func getItems(request: ___VARIABLE_moduleName___.DataContext.Request,
                   success: @escaping ([Any]) -> Void,
                   failure: @escaping (Error) -> Void)
}

class ___VARIABLE_moduleName___Service: ___VARIABLE_moduleName___ServiceProtocol {
  func getItems(request: ___VARIABLE_moduleName___.DataContext.Request,
                   success: @escaping ([Any]) -> Void,
                   failure: @escaping (Error) -> Void) {

  }
}
