//
//  WelcomeViewController.swift
//  VIPERExample
//
//  Created by Sergey Petrachkov on 13/09/2017.
//  Copyright (c) 2017 Sergey Petrachkov. All rights reserved.
//
//  This file was generated by the SergeyPetrachkov VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects
//

import UIKit

class WelcomeViewController: UIViewController {
  // MARK: - UI properties
  
  @IBOutlet weak var moreButton: UIButton!
  // MARK: - Essentials
  var presenter : WelcomePresenterInput?

  // MARK: Initializers
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
  }
  required init?(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)
  }
  
  // MARK: - Setup
  private func setup() {
    self.moreButton.layer.cornerRadius = 15
    self.moreButton.addTarget(self, action: #selector(self.moreTapped), for: .touchUpInside)
  }
  
  // MARK: - Actions
  @objc fileprivate func moreTapped() {
    self.presenter?.requestMore()
  }
  // MARK: - Lifecycle
  override func viewDidLoad() {
    super.viewDidLoad()
    self.setup()
  }
}
extension WelcomeViewController : WelcomePresenterOutput {
  func didChangeState(viewModel : Welcome.DataContext.ViewModel) {
    
  }
}
