//
//  WelcomeService.swift
//  VIPERExample
//
//  Created by Sergey Petrachkov on 13/09/2017.
//  Copyright (c) 2017 Sergey Petrachkov. All rights reserved.
//
//  This file was generated by the SergeyPetrachkov VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects.
//

import UIKit

class WelcomeService {
  func doSomeWork() {
  }
}
