//
//  DummyModuleService.swift
//  ActonicaTemplatesVIPER
//
//  Created by Sergey Petrachkov on 6/24/17.
//  Copyright (c) 2017 Sergey Petrachkov. All rights reserved.
//
//  This file was generated by the Actonica VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects.
//

import UIKit

class DummyModuleService
{
  func doSomeWork()
  {
  }
}
