//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the SergeyPetrachkov VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects
//

import UIKit

class ___VARIABLE_moduleName___ViewController: UITableViewController {
  // MARK: - UI properties
  
  // MARK: - Essentials
  var presenter: ___VARIABLE_moduleName___PresenterInput?

  // MARK: Initializers
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
  }
  required init?(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)
  }
  
  // MARK: - Setup
  fileprivate func setup() {
  }
  
  // MARK: - Lifecycle
  override func viewDidLoad() {
    super.viewDidLoad()
    self.setup()
  }

  // MARK: - Actions
}
extension ___VARIABLE_moduleName___ViewController: ___VARIABLE_moduleName___PresenterOutput {
  func didChangeState(viewModel: ___VARIABLE_moduleName___.DataContext.ViewModel) {
    
  }
}
