//
//  PlainCodeInteractor.swift
//  VIPERExample
//
//  Created by Sergey Petrachkov on 20/09/2017.
//  Copyright (c) 2017 Sergey Petrachkov. All rights reserved.
//
//  This file was generated by the SergeyPetrachkov VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects
//

import UIKit

protocol PlainCodeInteractorInput: class {
  var output : PlainCodeInteractorOutput? { get set }
  func doSomething(request: PlainCode.DataContext.Request)
}

protocol PlainCodeInteractorOutput: class {
  func didReceive(some data : Any)
  func didFail(with error: Error)
}


class PlainCodeInteractor: PlainCodeInteractorInput {
  let service: PlainCodeService = PlainCodeService()
  weak var output: PlainCodeInteractorOutput?
  
  // MARK: Do something
  func doSomething(request: PlainCode.DataContext.Request) {
    // Let's say we execute some async operation, then we want to be able to inform our output when the operation is finshed
    // self.service.requestSomeDataAsync(requestParams: params, 
    //                                          succes: {
    //                                            receivedData in
    //                                              self.output?.didReceive(some: receivedData)
    //                                          }),
    //                                          failure: {
    //                                            error in 
    //                                              NSLog("An error has occured while retrieving some data: \(error)")
    //                                              self.output?.didFail(error: error)
    //                                          })
    self.service.doSomeWork()
  }
}
