//
//  TabHostRouter.swift
//  EasiShare
//
//  Created by sergey on 30/04/2019.
//  Copyright (c) 2019 sergey. All rights reserved.
//
//  This file was generated by the Actonica VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects
//

import UIKit

protocol TabHostRoutingLogic {
//  func showSomething(from view: UIViewController, with routingParams : YourRoutingParams)
}


class TabHostRouter: TabHostRoutingLogic {
  // MARK: Routing
//  func showSomething(from view: UIViewController, with routingParams : YourRoutingParams) {
//    let nextVC = NextViewController()
//    nextVC.setup(with: routingParams)
//    view.navigationController?.push(nextVC, animated: true)
//  }
}
