//
//  TabHostPresenter.swift
//  EasiShare
//
//  Created by sergey on 30/04/2019.
//  Copyright (c) 2019 sergey. All rights reserved.
//
//  This file was generated by the SergeyPetrachkov VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects
//

import UIKit

protocol TabHostPresenterInput: class {
  var view: UIViewController! { get set }
  var output: TabHostPresenterOutput? { get set }
  var router: TabHostRoutingLogic? { get set }
  var interactor: TabHostInteractorInput? { get set }
  func presentSomething()
}
protocol TabHostPresenterOutput: class {
  func didChangeState(viewModel: TabHost.DataContext.ViewModel)
}

class TabHostPresenter: TabHostPresenterInput {
  // MARK: - Essentials
  weak var view: UIViewController!
  weak var output: TabHostPresenterOutput?
  var viewModel: TabHost.DataContext.ViewModel!
  var router: TabHostRoutingLogic?
  var interactor: TabHostInteractorInput?
  // MARK: - Initializers
  init(moduleIn: TabHost.DataContext.ModuleIn = TabHost.DataContext.ModuleIn()) {
    self.viewModel = TabHost.DataContext.ViewModel(moduleIn: moduleIn)
  }
  deinit {
    print("TabHostPresenter deinit is called")
  }
  // MARK: - Presenter Input
  func presentSomething() {
    // ask router to navigate somewhere or ask interactor for resources... it's up to you
    // like:
    // let requestParams = RequestParams()
    // self.interactor.getSomeData(requestParams: requestParams)
    // or:
    // let routingParams = RoutingParams(firstValue : self.viewModel.firstValue, secondValue: self.viewModel.secondValue)
    // self.router.showNextModule(from: self.view, with: routingParams)
  }
}
extension TabHostPresenter: TabHostInteractorOutput {
  // MARK: - Interactor output
  func didReceive(response: TabHost.DataContext.Response) {
    // Process it and act accordingly like:
    // self.output?.didChangeState(viewModel : )
  }
  func didFail(with error: Error) {
//    self.router.showError(error: error)
  }
}
