//
//  TabHostService.swift
//  EasiShare
//
//  Created by sergey on 30/04/2019.
//  Copyright (c) 2019 sergey. All rights reserved.
//
//  This file was generated by the SergeyPetrachkov VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects.
//

import UIKit

protocol TabHostServiceProtocol: class {
  func doSomeWork()	
}

class TabHostService: TabHostServiceProtocol {
  func doSomeWork() {
  }
}
