//
//  TabHostEntities.swift
//  EasiShare
//
//  Created by sergey on 30/04/2019.
//  Copyright (c) 2019 sergey. All rights reserved.
//
//  This file was generated by the SergeyPetrachkov VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects
//

import UIKit

enum TabHost {
  // MARK: - Use cases
  enum DataContext {
  	struct ModuleIn {
  	}
  	struct ModuleOut {
  	}
    struct Request {
    }
    struct Response {
    }
    struct ViewModel {
      init(moduleIn: ModuleIn) {
      	
      }
    }
  }
}
