//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the SergeyPetrachkov VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects
//

import UIKit

class TabHostViewController: UITabBarController {
  // MARK: - UI properties
  
  // MARK: - Essentials
  var presenter: TabHostPresenterInput?
 
  // MARK: - Setup
  fileprivate func setup() {
  }
  
  // MARK: - Lifecycle
  override func viewDidLoad() {
    super.viewDidLoad()
    self.setup()
  }

  // MARK: - Actions
}

extension TabHostViewController: TabHostPresenterOutput {
  func didChangeState(viewModel: TabHost.DataContext.ViewModel) {
    
  }
}
