//
//  TabHostInteractor.swift
//  EasiShare
//
//  Created by sergey on 30/04/2019.
//  Copyright (c) 2019 sergey. All rights reserved.
//
//  This file was generated by the SergeyPetrachkov VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects
//

import UIKit

protocol TabHostInteractorInput: class {
  var output: TabHostInteractorOutput? { get set }
  func requestData(request: TabHost.DataContext.Request)
}

protocol TabHostInteractorOutput: class {
  func didReceive(response: TabHost.DataContext.Response)
  func didFail(with error: Error)
}

class TabHostInteractor: TabHostInteractorInput {
  let service: TabHostServiceProtocol = TabHostService()
  weak var output: TabHostInteractorOutput?
  
  // MARK: - Input
  func requestData(request: TabHost.DataContext.Request) {
    // Let's say we execute some async operation, then we want to be able to inform our output when the operation is finshed
    // self.service.requestSomeDataAsync(requestParams: params, 
    //                                          succes: {
    //                                            receivedData in
    //                                              self.output?.didReceive(some: receivedData)
    //                                          }),
    //                                          failure: {
    //                                            error in 
    //                                              NSLog("An error has occured while retrieving some data: \(error)")
    //                                              self.output?.didFail(error: error)
    //                                          })
    self.service.doSomeWork()
  }
}
