//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the SergeyPetrachkov VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects
//

import UIKit
import SiberianVIPER
protocol ___VARIABLE_moduleName___MapperProtocol: CollectionModuleMapper {
  
}
class ___VARIABLE_moduleName___Mapper: ___VARIABLE_moduleName___MapperProtocol {
  
  typealias EntityType = Any
  
  typealias ViewModelType = ___VARIABLE_moduleName___Model

  func map(items: [Any]) -> [___VARIABLE_moduleName___Model] {
    return items.map( { ___VARIABLE_moduleName___Model(currentModel: $0) } )
  }

  // func map(request: ___VARIABLE_moduleName___.DataContext.Request) -> ___VARIABLE_moduleName___.DataContext.Response {
  //   return ___VARIABLE_moduleName___.DataContext.Response(originalRequest: (originalRequest: request))
  // }
}
