//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Actonica VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects
//

import UIKit

protocol ___VARIABLE_moduleName___RoutingLogic {
}


class ___VARIABLE_moduleName___Router: ___VARIABLE_moduleName___RoutingLogic {
  // MARK: Routing
}
