//
//  ListInteractor.swift
//  VIPERExample
//
//  Created by Sergey Petrachkov on 26/12/2017.
//  Copyright (c) 2017 Sergey Petrachkov. All rights reserved.
//
//  This file was generated by the SergeyPetrachkov VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects
//

import UIKit

protocol ListInteractorInput: class {
  var output: ListInteractorOutput? { get set }
  func requestData(request: List.DataContext.Request)
}

protocol ListInteractorOutput: class {
  func didReceive(response: List.DataContext.Response)
  func didFail(with error: Error)
}

class ListInteractor: ListInteractorInput {
  let service: ListServiceProtocol = ListService()
  weak var output: ListInteractorOutput?
  
  // MARK: - Input
  func requestData(request: List.DataContext.Request) {
    // Let's say we execute some async operation, then we want to be able to inform our output when the operation is finshed
    // self.service.requestSomeDataAsync(requestParams: params, 
    //                                          succes: {
    //                                            receivedData in
    //                                              self.output?.didReceive(some: receivedData)
    //                                          }),
    //                                          failure: {
    //                                            error in 
    //                                              NSLog("An error has occured while retrieving some data: \(error)")
    //                                              self.output?.didFail(error: error)
    //                                          })
    self.service.doSomeWork()
  }
}
