//
//  ListAssembly.swift
//  VIPERExample
//
//  Created by Sergey Petrachkov on 26/12/2017.
//  Copyright (c) 2017 Sergey Petrachkov. All rights reserved.
//
//  This file was generated by the SergeyPetrachkov VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects
//

import UIKit

class ListAssembly {
  // MARK: - Constants
  fileprivate static let storyboardId = "Module"
  fileprivate static let controllerStoryboardId = "List"
  // MARK: - Public methods
  static func createModule(moduleIn: List.DataContext.ModuleIn) -> ListViewController {
    if let controller = UIStoryboard(name: storyboardId, bundle: nil).instantiateViewController(withIdentifier: controllerStoryboardId) as? ListViewController {
      let presenter = injectPresenter(moduleIn: moduleIn)
      presenter.output = controller
      presenter.view = controller
      controller.presenter = presenter
      return controller
    } else {
      fatalError("Could not create List module!!! Check List assembly")
    }
  }
  // MARK: - Private injections
  fileprivate static func injectPresenter(moduleIn: List.DataContext.ModuleIn) -> ListPresenterInput {
    let presenter = ListPresenter(moduleIn: moduleIn)
    let interactor = injectInteractor()
    interactor.output = presenter
    presenter.interactor = interactor
    let router = injectRouter()
    presenter.router = router
    return presenter
  }
  fileprivate static func injectInteractor() -> ListInteractorInput {
    return ListInteractor()
  }
  fileprivate static func injectRouter() -> ListRoutingLogic {
    return ListRouter()
  }
}