//
//  ListPresenter.swift
//  VIPERExample
//
//  Created by Sergey Petrachkov on 26/12/2017.
//  Copyright (c) 2017 Sergey Petrachkov. All rights reserved.
//
//  This file was generated by the SergeyPetrachkov VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects
//

import UIKit

protocol ListPresenterInput: class {
  var view: UIViewController! { get set }
  var output: ListPresenterOutput? { get set }
  var router: ListRoutingLogic? { get set }
  var interactor: ListInteractorInput? { get set }
  func presentSomething()
}
protocol ListPresenterOutput: class {
  func didChangeState(viewModel : List.DataContext.ViewModel)
}

class ListPresenter: ListPresenterInput {
  // MARK: - Essentials
  weak var view: UIViewController!
  weak var output: ListPresenterOutput?
  var viewModel: List.DataContext.ViewModel!
  var router: ListRoutingLogic?
  var interactor: ListInteractorInput?
  // MARK: - Initializers
  init(moduleIn: List.DataContext.ModuleIn) {
    self.viewModel = List.DataContext.ViewModel(moduleIn: moduleIn)
  }
  deinit {
    print("ListPresenter deinit is called")
  }
  // MARK: - Presenter Input
  func presentSomething() {
    // ask router to navigate somewhere or ask interactor for resources... it's up to you
    // like:
    // let requestParams = RequestParams()
    // self.interactor.getSomeData(requestParams: requestParams)
    // or:
    // let routingParams = RoutingParams(firstValue : self.viewModel.firstValue, secondValue: self.viewModel.secondValue)
    // self.router.showNextModule(from: self.view, with: routingParams)
  }
}
extension ListPresenter: ListInteractorOutput {
  // MARK: - Interactor output
  func didReceive(response: List.DataContext.Response) {
    // Process it and act accordingly like:
    // self.output?.didChangeState(viewModel : )
  }
  func didFail(with error: Error) {
//    self.router.showError(error: error)
  }
}